version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg17
    container_name: postgres_db
    ports:
      - "5490:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    environment:
      - DATABASE_URL=postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@{DB_HOST}:{DB_PORT}/${DB_NAME}   
    ports:
      - "8009:8009"
      - "5678:5678"
    depends_on:
      - db
volumes:
  postgres_data: